// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/messages.proto

package app;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:app.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .app.Message.RequestType opCode = 1;</code>
     */
    boolean hasOpCode();
    /**
     * <code>required .app.Message.RequestType opCode = 1;</code>
     */
    app.Messages.Message.RequestType getOpCode();

    /**
     * <code>optional string fileName = 2;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional int32 blockNum = 3;</code>
     */
    boolean hasBlockNum();
    /**
     * <code>optional int32 blockNum = 3;</code>
     */
    int getBlockNum();

    /**
     * <code>optional bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional .app.Message.ErrCode errCode = 5;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional .app.Message.ErrCode errCode = 5;</code>
     */
    app.Messages.Message.ErrCode getErrCode();

    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code app.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:app.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      opCode_ = 1;
      fileName_ = "";
      blockNum_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      errCode_ = 1;
      errMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              app.Messages.Message.RequestType value = app.Messages.Message.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opCode_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              fileName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              blockNum_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              app.Messages.Message.ErrCode value = app.Messages.Message.ErrCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                errCode_ = rawValue;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              errMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.Messages.internal_static_app_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.Messages.internal_static_app_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.Messages.Message.class, app.Messages.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code app.Message.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RRQ = 1;</code>
       */
      RRQ(1),
      /**
       * <code>WRQ = 2;</code>
       */
      WRQ(2),
      /**
       * <code>DATA = 3;</code>
       */
      DATA(3),
      /**
       * <code>ACK = 4;</code>
       */
      ACK(4),
      /**
       * <code>ERROR = 5;</code>
       */
      ERROR(5),
      ;

      /**
       * <code>RRQ = 1;</code>
       */
      public static final int RRQ_VALUE = 1;
      /**
       * <code>WRQ = 2;</code>
       */
      public static final int WRQ_VALUE = 2;
      /**
       * <code>DATA = 3;</code>
       */
      public static final int DATA_VALUE = 3;
      /**
       * <code>ACK = 4;</code>
       */
      public static final int ACK_VALUE = 4;
      /**
       * <code>ERROR = 5;</code>
       */
      public static final int ERROR_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      public static RequestType forNumber(int value) {
        switch (value) {
          case 1: return RRQ;
          case 2: return WRQ;
          case 3: return DATA;
          case 4: return ACK;
          case 5: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return app.Messages.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:app.Message.RequestType)
    }

    /**
     * Protobuf enum {@code app.Message.ErrCode}
     */
    public enum ErrCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FileNotFound = 1;</code>
       */
      FileNotFound(1),
      /**
       * <code>AccessViolation = 2;</code>
       */
      AccessViolation(2),
      ;

      /**
       * <code>FileNotFound = 1;</code>
       */
      public static final int FileNotFound_VALUE = 1;
      /**
       * <code>AccessViolation = 2;</code>
       */
      public static final int AccessViolation_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ErrCode valueOf(int value) {
        return forNumber(value);
      }

      public static ErrCode forNumber(int value) {
        switch (value) {
          case 1: return FileNotFound;
          case 2: return AccessViolation;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ErrCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrCode>() {
              public ErrCode findValueByNumber(int number) {
                return ErrCode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return app.Messages.Message.getDescriptor().getEnumTypes().get(1);
      }

      private static final ErrCode[] VALUES = values();

      public static ErrCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ErrCode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:app.Message.ErrCode)
    }

    private int bitField0_;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private int opCode_;
    /**
     * <code>required .app.Message.RequestType opCode = 1;</code>
     */
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .app.Message.RequestType opCode = 1;</code>
     */
    public app.Messages.Message.RequestType getOpCode() {
      app.Messages.Message.RequestType result = app.Messages.Message.RequestType.valueOf(opCode_);
      return result == null ? app.Messages.Message.RequestType.RRQ : result;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 2;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string fileName = 2;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCKNUM_FIELD_NUMBER = 3;
    private int blockNum_;
    /**
     * <code>optional int32 blockNum = 3;</code>
     */
    public boolean hasBlockNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 blockNum = 3;</code>
     */
    public int getBlockNum() {
      return blockNum_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 5;
    private int errCode_;
    /**
     * <code>optional .app.Message.ErrCode errCode = 5;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .app.Message.ErrCode errCode = 5;</code>
     */
    public app.Messages.Message.ErrCode getErrCode() {
      app.Messages.Message.ErrCode result = app.Messages.Message.ErrCode.valueOf(errCode_);
      return result == null ? app.Messages.Message.ErrCode.FileNotFound : result;
    }

    public static final int ERRMSG_FIELD_NUMBER = 6;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ErrMsg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, blockNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, errCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, blockNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, errCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof app.Messages.Message)) {
        return super.equals(obj);
      }
      app.Messages.Message other = (app.Messages.Message) obj;

      boolean result = true;
      result = result && (hasOpCode() == other.hasOpCode());
      if (hasOpCode()) {
        result = result && opCode_ == other.opCode_;
      }
      result = result && (hasFileName() == other.hasFileName());
      if (hasFileName()) {
        result = result && getFileName()
            .equals(other.getFileName());
      }
      result = result && (hasBlockNum() == other.hasBlockNum());
      if (hasBlockNum()) {
        result = result && (getBlockNum()
            == other.getBlockNum());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasErrCode() == other.hasErrCode());
      if (hasErrCode()) {
        result = result && errCode_ == other.errCode_;
      }
      result = result && (hasErrMsg() == other.hasErrMsg());
      if (hasErrMsg()) {
        result = result && getErrMsg()
            .equals(other.getErrMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOpCode()) {
        hash = (37 * hash) + OPCODE_FIELD_NUMBER;
        hash = (53 * hash) + opCode_;
      }
      if (hasFileName()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFileName().hashCode();
      }
      if (hasBlockNum()) {
        hash = (37 * hash) + BLOCKNUM_FIELD_NUMBER;
        hash = (53 * hash) + getBlockNum();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + errCode_;
      }
      if (hasErrMsg()) {
        hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static app.Messages.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.Messages.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.Messages.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.Messages.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.Messages.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.Messages.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.Messages.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static app.Messages.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static app.Messages.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static app.Messages.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static app.Messages.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static app.Messages.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(app.Messages.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:app.Message)
        app.Messages.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.Messages.internal_static_app_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.Messages.internal_static_app_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.Messages.Message.class, app.Messages.Message.Builder.class);
      }

      // Construct using app.Messages.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        opCode_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        blockNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        errCode_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.Messages.internal_static_app_Message_descriptor;
      }

      public app.Messages.Message getDefaultInstanceForType() {
        return app.Messages.Message.getDefaultInstance();
      }

      public app.Messages.Message build() {
        app.Messages.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.Messages.Message buildPartial() {
        app.Messages.Message result = new app.Messages.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opCode_ = opCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.blockNum_ = blockNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.Messages.Message) {
          return mergeFrom((app.Messages.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.Messages.Message other) {
        if (other == app.Messages.Message.getDefaultInstance()) return this;
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000002;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasBlockNum()) {
          setBlockNum(other.getBlockNum());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000020;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.Messages.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.Messages.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int opCode_ = 1;
      /**
       * <code>required .app.Message.RequestType opCode = 1;</code>
       */
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .app.Message.RequestType opCode = 1;</code>
       */
      public app.Messages.Message.RequestType getOpCode() {
        app.Messages.Message.RequestType result = app.Messages.Message.RequestType.valueOf(opCode_);
        return result == null ? app.Messages.Message.RequestType.RRQ : result;
      }
      /**
       * <code>required .app.Message.RequestType opCode = 1;</code>
       */
      public Builder setOpCode(app.Messages.Message.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .app.Message.RequestType opCode = 1;</code>
       */
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opCode_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 2;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }

      private int blockNum_ ;
      /**
       * <code>optional int32 blockNum = 3;</code>
       */
      public boolean hasBlockNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 blockNum = 3;</code>
       */
      public int getBlockNum() {
        return blockNum_;
      }
      /**
       * <code>optional int32 blockNum = 3;</code>
       */
      public Builder setBlockNum(int value) {
        bitField0_ |= 0x00000004;
        blockNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 blockNum = 3;</code>
       */
      public Builder clearBlockNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockNum_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int errCode_ = 1;
      /**
       * <code>optional .app.Message.ErrCode errCode = 5;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .app.Message.ErrCode errCode = 5;</code>
       */
      public app.Messages.Message.ErrCode getErrCode() {
        app.Messages.Message.ErrCode result = app.Messages.Message.ErrCode.valueOf(errCode_);
        return result == null ? app.Messages.Message.ErrCode.FileNotFound : result;
      }
      /**
       * <code>optional .app.Message.ErrCode errCode = 5;</code>
       */
      public Builder setErrCode(app.Messages.Message.ErrCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        errCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .app.Message.ErrCode errCode = 5;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errCode_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000020);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ErrMsg = 6;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        errMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:app.Message)
    }

    // @@protoc_insertion_point(class_scope:app.Message)
    private static final app.Messages.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new app.Messages.Message();
    }

    public static app.Messages.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public app.Messages.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_app_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_app_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protobuf/messages.proto\022\003app\"\215\002\n\007Messa" +
      "ge\022(\n\006opCode\030\001 \002(\0162\030.app.Message.Request" +
      "Type\022\020\n\010fileName\030\002 \001(\t\022\020\n\010blockNum\030\003 \001(\005" +
      "\022\014\n\004data\030\004 \001(\014\022%\n\007errCode\030\005 \001(\0162\024.app.Me" +
      "ssage.ErrCode\022\016\n\006ErrMsg\030\006 \001(\t\"=\n\013Request" +
      "Type\022\007\n\003RRQ\020\001\022\007\n\003WRQ\020\002\022\010\n\004DATA\020\003\022\007\n\003ACK\020" +
      "\004\022\t\n\005ERROR\020\005\"0\n\007ErrCode\022\020\n\014FileNotFound\020" +
      "\001\022\023\n\017AccessViolation\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_app_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_app_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_app_Message_descriptor,
        new java.lang.String[] { "OpCode", "FileName", "BlockNum", "Data", "ErrCode", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
